import random
position = [ 'RNNQKBBR', 'RBBQKNNR', 'RNNKQBBR','RBBKQNNR', 'RBNQKNBR', 'RBNKQNBR', 'RQKNNBBR', 'RKQNNBBR','RQKBBNNR', 'RKQBBNNR', 'RNNBBQKR', 'RNNBBKQR', 'RKNNBBQR', 'RKBBNNQR', 'RQNNBBKR', 'RQBBNNKR', 'RKNBBNQR', 'RQNBBNKR', 'RKBNNBQR', 'RQBNNBKR' ]
print(random.choice(position))
